# Generated by Django 5.0.4 on 2024-05-01 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField()),
                ('fechaFin', models.DateField(blank=True)),
                ('categoria', models.CharField(max_length=100)),
                ('metodo_pago', models.CharField(max_length=50)),
                ('notas', models.TextField(blank=True)),
                ('pagoUnico', models.BooleanField(default=False)),
                ('frecuencia', models.CharField(blank=True, choices=[('mensual', 'Mensual'), ('semanal', 'Semanal'), ('anual', 'Anual')], max_length=10, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
