# Generated by Django 5.0.4 on 2024-05-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoinControllapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='fechaFin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
