# Generated by Django 5.0.4 on 2024-05-11 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoinControllapp', '0004_ingreso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingreso',
            old_name='fecha_inicio',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='ingreso',
            old_name='fecha_fin',
            new_name='fechaFin',
        ),
    ]
