# Generated by Django 5.0.4 on 2024-05-12 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoinControllapp', '0006_ingreso_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingreso',
            old_name='monto',
            new_name='cantidad',
        ),
    ]
